### ISSUE TITLE
Blogs  component design 

### ISSUE THREAD

**Issue by AASB7** [AASB7/Training_Project#15]
**Task title**
Blogs  component design 

**Task description**
Design Blogs  component as shown in the screenshot, responsive and add it to the layouts file

**Subtasks**
- [ ] make sure all assets exist (images/icons, fonts ...), to be able to use them.
- [ ] apply responsiveness.

**Screenshots**
![Capture](https://github.com/AASB7/Training_Project/assets/96662087/869ac016-a4c3-44d8-a807-f57791ace074)

**Link to the component on Figma**
https://www.figma.com/file/1twnLRHlT4mYrNutDxrXCZ/gpt3-(Copy)?type=design&node-id=0-15&t=5Vns0vqYXFb9F03U-0

**Comment by Aryam57** [comment]
good job.
